[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = false
extra_output = ["storageLayout"]

# Fork configuration should be here, not in rpc_endpoints
fork_url = "${RPC_URL}"
fork_block_number = 21596000

[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz = { runs = 10000 }
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
