[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
bsc_archive = "${BSC_ARCHIVE_RPC}"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true